#pragma once
#include <iostream>
#include <memory>

#ifdef RAY_OPTIX
#include <optix.h>
#include <optix_function_table_definition.h>
#include <optix_stack_size.h>
#include <optix_stubs.h>

// Custom optix toolchain stuff
// #  include "optix/raytrace.h"

#include "optix/program.h"

// Compiled optix program PTX generated by cmake and wrapped in a C
// header by bin2c.
// namespace optix_ptx {
// 	#include <optix_ptx.h>
// }
#endif  // RAY_OPTIX
